### ISSUE TITLE
Null error continuation

### ISSUE THREAD

**Issue by Astrareach** [DenizenScript/dDiscordBot#12]
(continuation of https://github.com/DenizenScript/dDiscordBot/issues/11)

Greeting, I have made sure to use the new version (19) and verify multiple time the channel id and proprer token etc. I got the same problem :

**Full server log** : https://pastebin.com/VxfUcMaJ

**Comment by mcmonkey4eva** [comment]
The bot was likely not yet loaded when you ran the command.

If the issue is just more of #11, post as a reply to #11, not a new issue.
