### ISSUE TITLE
change Discord4J dependency

### ISSUE THREAD

**Issue by Mwthorn** [DenizenScript/dDiscordBot#14]
The current Discord4J dependency, this project uses, is no longer being maintained.
It might not be much of an issue now, but it will most likely be in the near future (when it no longer can use the Discord API for a specific version). Adding new features will also become a problem.

The oudated source: https://github.com/nerd/Discord4J

The new forked source: https://github.com/Discord4J/Discord4J

**Comment by mcmonkey4eva** [comment]
I have no idea why you think that particular source is in use. It is not.
https://github.com/Discord4J/Discord4J/tree/2.x is in use.

The change needed is an eventual upgrade from 2.x to 3.x
(For reference, 2.x was the officially recommended version up until late February this year)
