### ISSUE TITLE
add tag: user's roles

### ISSUE THREAD

**Issue by Mwthorn** [DenizenScript/dDiscordBot#15]
I would like a tag that returns a list of a user's roles. There are a few ways to make this work, here are some of the options I can think of:
1. Make a new object called `member` which is pretty much the same as `user` but for an object in a group.
2. Extend the user object and give the tag a group input <discorduser@user.roles[<discordgroup@group>]>

I prefer option 2 since it feels more simple but I want to know what others think of this.

**Comment by mcmonkey4eva** [comment]
I did this already yesterday but forgot to finish testing and commit
