### ISSUE TITLE
Add "Bot is typing..."

### ISSUE THREAD

**Issue by Mwthorn** [DenizenScript/dDiscordBot#17]
A discord bot has a feature to show that it is "typing".
Quite a silly feature and is mainly just for "roleplay/visual" things I guess. I still like it though :)

Command suggestion:
`- discord typing false`
`- discord typing true`

**Comment by mcmonkey4eva** [comment]
The Discord4J API is absolutely awful, as every Java developer seems to have to have their own incoherent custom language design system rather than just using Java the normal way. Either way, added. Requires a channel ID be input, of course.
