### ISSUE TITLE
Modify/Delete messages

### ISSUE THREAD

**Issue by Mwthorn** [DenizenScript/dDiscordBot#18]
A command to modify/delete messages in a text channel:
- discord id:myBot message msg_id:1234567890 "This is my modified text"
- discord id:myBot message msg_id:1234567890
If no text input is given, it deletes the message instead. And of course, if no `msg_id` is given, it creates a new message.

The message related events needs a `<context.message_id>` to support this feature.

Also there needs to be some kind of way to have the message ID returned after being sent by a bot. Maybe the `save` arguement can be used?

**Comment by mcmonkey4eva** [comment]
Added all 3 requests, as 3 separate commits.
