### ISSUE TITLE
Embed messages

### ISSUE THREAD

**Issue by Mwthorn** [DenizenScript/dDiscordBot#20]
I think there is a possible way to make a embedded message in denizen by using ids (just like bossbar, sql, yaml ect.)
Here is how I think it could go:
- embed create id:<[embed_id]> title:"wow" description:"much wow" url:<[link]> timestamp:<[date]> color:<[color]> image:<[url]> thumbnail:<[url]>
- embed remove id:<[embed_id]>
- embed setfooter id:<[embed_id]> icon_url:<[link]> text:"This is cool"
- embed setauther id:<[embed_id]> name:"very wow" url:<[link]> icon_url:<[link]>
- embed addfield id:<[embed_id]> name:"very wow" value:"This is cool"
- embed addfield id:<[embed_id]> name:"very much" value:"This is very cool" inline
Commands were inspiration from: https://leovoel.github.io/embed-visualizer/

Then, once we want to send the embedded message, we could perhaps do:
- discord id:mybot message channel:<discord[mybot].group[Denizen].channel[bot-spam]> embed:<[embed_id]>
or maybe:
- discord id:mybot send_embed channel:<discord[mybot].group[Denizen].channel[bot-spam]> embed:<[embed_id]>

Another way of doing this might be to make the entire embed message through the discord command instead of a separated embed command.

**Comment by mcmonkey4eva** [comment]
Embed would work much better as an object type

**Comment by Mwthorn** [comment]
I'm curious to try and implement this but I'm not sure how this object type you mention should be made.
Using tags or cmds? Maybe using a format way like:
`MyScriptName:
    type: embed
    bla bla bla...`

**Comment by mcmonkey4eva** [comment]
added DiscordEmbedTag
