### ISSUE TITLE
add status and activity tags for DiscordUserTag

### ISSUE THREAD

**Issue by Mwthorn** [DenizenScript/dDiscordBot#22]
`<DiscordUserTag.status>`
The status should return a ElementTag which can either be ONLINE, DND, IDLE, or INVISIBLE.

`<DiscordUserTag.activity>`
The activity should return a ElementTag which can either be PLAYING, STREAMING, LISTENING, or WATCHING. Additionally the tag should include the activity the user is doing or maybe split it up with `<DiscordUserTag.activity_type>`.

**Comment by mcmonkey4eva** [comment]
It seems like this information (presence) is locked to guild membership in Discord4j. Weird.
