### ISSUE TITLE
Error fired on startup

### ISSUE THREAD

**Issue by MrMaleficus** [DenizenScript/dDiscordBot#27]
Since the last updates, my dDiscordBot is a bit angry when my server finish to start-up.

Here the debug : https://one.denizenscript.com/haste/62319
Here the script : https://one.denizenscript.com/haste/62321

Important note : The message is correctly send anyway.

```
> version ddiscordbot
[20:55:26 INFO]: dDiscordBot version 0.6 (build 60)
[20:55:26 INFO]: Author: mcmonkey
```

**Comment by Ph4i1ur3** [comment]
Are you positive this script is the only one accessing the bot?

**Comment by Ph4i1ur3** [comment]
I ask because the error is seemingly coming from trying to access this channel: "534015601157603338"
And your script references this channel: "533827537256579072"

**Comment by MrMaleficus** [comment]
My bot is used by many parts of my scripts but I can assure you i have no channel identified by the id `534015601157603338` in my scripts

**Comment by SXRWahrheit** [comment]
That is not a debug - please provide a full debug using the proper procedure.

**Comment by Ph4i1ur3** [comment]
To be clear, this happens during startup, and not anytime a message is sent?

**Comment by MrMaleficus** [comment]
Here it is : https://one.denizenscript.com/paste/62322
@Ph4i1ur3 yes, it happens when the server has loaded all scripts and stuff

**Comment by SXRWahrheit** [comment]
The error appears to happen upon *connection,* not startup. Is that the full script / all the dDiscordBot scripts you use?

**Comment by mcmonkey4eva** [comment]
The error exists within Discord itself or Discord4J (the backing API). It seems to just be angry about gathering a list of channels. It looks like Discord sent back a list of channels, but then denied the bot access to reading basic metadata from at least one of those channels, which... wat?

Not much I can do from my end other than never trying to list channels, which, y'know, is kinda useful to be able to do.
