### ISSUE TITLE
deprecation warning in deleted message event

### ISSUE THREAD

**Issue by Mwthorn** [DenizenScript/dDiscordBot#29]
<context.author> is written correctly (as both shown in code and meta) but it gives a warning for `<context.author_name>` and suggests `<context.user.id>` which is not valid.
https://one.denizenscript.com/paste/64920#38

Also it seems deleted messages event are always non-valid, even if I sent the message 10 seconds ago and deleted it afterwards (in log). Has the cache feature been tested?

**Comment by mcmonkey4eva** [comment]
Caching is a feature of Discord4j, not dDiscordBot. Whether the cache works is up to Discord4J working, which it doesn't tend to do in general.

That deprecation is a general error message, note the `and similar contexts` part - it is triggered by your usage of `channel_name`, which falls under the list of contexts of the `_name` format that have been deprecated.
