### ISSUE TITLE
1.13.x versions

### ISSUE THREAD

**Issue by 21stCheran** [DenizenScript/dDiscordBot#5]
I would love it if you can update this plugin to 1.13.2 the latest version does not work on 1.13.2

**Comment by mcmonkey4eva** [comment]
is there an error with it? If so, can you please post it

**Comment by 21stCheran** [comment]
https://pastebin.com/xJgcQCnb

**Comment by mcmonkey4eva** [comment]
That's not a 1.13 compatibility error. If anything it looks like a corrupted jar (which is fixed by redownloading it) or a duplicated / similarly borked plugin jar.

The other possibility is that there's a different error in your logs that you didn't include.
