### ISSUE TITLE
Discord Functionality Support

### ISSUE THREAD

**Issue by robgob** [DenizenScript/dDiscordBot#7]
Hello All,

Would it be possible to add support to allow the discord bot to run commands on the server and assign roles? (Example: A player votes so many times, they get moved to the TopVoters role on the discord server)

Or allow the bot to send channel updates such as the channel topic, ban users, and such..

**Comment by mcmonkey4eva** [comment]
@mwthorn is working on this in PR #6

**Comment by robgob** [comment]
Thank you! :D

**Comment by mcmonkey4eva** [comment]
NewStuff.jpg available in new builds.
